### ISSUE TITLE
preview for sharing

### ISSUE THREAD

**Issue by krrisis** [Giveth/wall-of-fame#33]
when sharing on other platforms (fb, twttr etc) it should be able to fetch a preview of the text + vid (even if it's just a screenshot)

**Comment by geleeroyale** [comment]
1 - Generate a thumbnail for each video
2 - Modify the 'share-view' to include these opengraph tags - variables are pseudo code:

`
<meta property="og:title" content={videoTitle} />
<meta property="og:type" content="video.other" />
<meta property="og:url" content={videoURL} />
<meta property="og:image" content={generatedThumnail} />
`

**Comment by deamme** [comment]
Meta tags needs to be rendered from the first request to the server which is not possible with Netlify as we are using it right now. If this is a must then we need to pre-render things somehow, using e.g. https://www.netlify.com/docs/prerendering/. Netlify is only for Single Page Applications right?

**Comment by krrisis** [comment]
yeah, to me this definitely is a must. these videos have the most value if we're able to share them. will let geleeroyale come back on the tech Qs

**Comment by deamme** [comment]
This is a bigger project and we should probably move to something like https://zeit.co/now and use https://github.com/zeit/next.js/.

**Comment by geleeroyale** [comment]
Oh @deamme I am so intrigued by now and next.js - Had a look at that a few weeks back. But this is seriously blowing up scope.

I guess this is up to you @deamme - You have been diving into the code of walloffame for some time now. Seeing that all dependencies are out of date anyway and @eduadiez does not have the time-ressources to keep it maintained, rebuilding the whole project could very well pay off.

I do not know if **anybody tries tackling IPFS right now on this build** - @maxskant ? @eduadiez ? - otherwise I am open to move and learn how to work with nextjs.

**Comment by maxskant** [comment]
@geleeroyale From what I understood, it sounds like we're waiting for SwarmCity and the IPFS Consortium to get things up and running. So we probably can't use IPFS right now.

**Comment by maxskant** [comment]
(Didn't mean to close this issue!)

**Comment by geleeroyale** [comment]
No problem and thanks @maxskant - we are going ahead with restructuring the project eith nextjs in the meantime

**Comment by GriffGreen** [comment]
It seems like uploading the vids to another service (like youtube) while we wait for ipfs would be a lot easier than rewriting the entire backend... @deamme and @geleeroyale what do you think?

**Comment by deamme** [comment]
Sharing youtube links gives us the preview side of things and we can get traffic to the Giveth youtube channel (if we decide to upload them there). The cons though would be that we need to find a way to integrate youtube into the current wall of fame site - not only dealing with the youtube player api but also the api for uploading. Another issue would be that we won't get any traffic back to the wall of fame site for sharing a link because it's a youtube link.

**Comment by geleeroyale** [comment]
@GriffGreen IPFS integration and preview features are not related. I merely wanted to check back if somebody still develops advanced features on the current codebase.

@deamme I found [react-helmet](https://github.com/nfl/react-helmet). Could we use this to dynamically change `<meta>` tags in `<head>` on the share video page?

**Comment by deamme** [comment]
@geleeroyale It will create it after a page load but Twitter and Facebook doesn't load your page it can only tell from the first server response (what I know of).

**Comment by geleeroyale** [comment]
Well they cache your response - they still have to load it once. I think it might be possible to use router in a way that Useragents-bots from social sites get their own routing. Not sure though. It is definitely possible if we have a dedicated middleware.

**Comment by geleeroyale** [comment]
Also found [this discussion on stackexchange](https://stackoverflow.com/questions/37734150/how-to-update-meta-tags-in-react-js)

**Comment by deamme** [comment]
I haven't tried it but I'm quite sure that it won't work. Facebook, Twitter etc. is only using the HTML from the first response (they don't load any javascript). It's the javascript that changes meta and title if we use something like react-helmet and that's why we need server-side rendering.
